### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by HGamal11** [FlashTek/attention-is-all-you-need-keras#1]
I was just trying to create a model using this code 

```
training_model, inference_model = create_model(source_vocabulary_size=98,target_vocabulary_size=98,max_length=20, share_word_embedding=False,n=6, h=8, d_k=64, d_v=64, d_model=512, optimizer="adam", null_token_value=98)

model.summary()

```

I get that error 

  File "aisayn.py", line 5, in <module>
    n=6, h=8, d_k=64, d_v=64, d_model=512, optimizer="adam", null_token_value=98)
  File "/home/hebagamal/keras-retinanet/modelcl.py", line 172, in create_model
    n=n, h=h, d_k=d_k, d_v=d_v,d_model=d_model, optimizer=optimizer, null_token_value=null_token_value)
  File "/home/hebagamal/keras-retinanet/modelcl.py", line 145, in build_transformer
    enc_output = enc(enc_input)
  File "/home/hebagamal/keras-retinanet/modelcl.py", line 88, in __call__
    x = layer(x)
  File "/home/hebagamal/keras-retinanet/modelcl.py", line 33, in __call__
    x = self._ln_a(y)
  File "/usr/lib64/python3.6/site-packages/keras/engine/topology.py", line 592, in __call__
    self.build(input_shapes[0])
  File "/usr/lib/python3.6/site-packages/kulc/layer_normalization.py", line 45, in build
    trainable=True
  File "/usr/lib64/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/keras/engine/topology.py", line 413, in add_weight
    weight = K.variable(initializer(shape),
  File "/usr/lib64/python3.6/site-packages/keras/initializers.py", line 46, in __call__
    return K.constant(1, shape=shape, dtype=dtype)
  File "/usr/lib64/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 423, in constant
    return tf.constant(value, dtype=dtype, shape=shape, name=name)
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 208, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 380, in make_tensor_proto
    if shape is not None and np.prod(shape, dtype=np.int64) == 0:
  File "/usr/lib64/python3.6/site-packages/numpy/core/fromnumeric.py", line 2585, in prod
    initial=initial)
  File "/usr/lib64/python3.6/site-packages/numpy/core/fromnumeric.py", line 83, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by zimmerrol** [comment]
Hello,
there has been an issue with the `Attention` modules of `kulc`. The problem had already been fixed in the latest commit, but not in the latest `pip` package. I released a new version of the latter today. Furthermore, I fixed some typos in this repo, so just pull this repo again and update `kulc` via `pip`. This should fix the issue.

**Comment by HGamal11** [comment]
Thanks for your reply 
I did that and I am still getting the same error

**Comment by zimmerrol** [comment]
Please try to use the latest version of `kulc`, which is `0.0.8`. This should work.

**Comment by HGamal11** [comment]
Its working thank you
